In [13]:
import pandas as pd
df = pd.read_csv(r'D:\Personal\diksha\6 SEM\NLP-shivi\Buck\Research_Paper_Category_Dataset_v3.csv', encoding='latin-1')
df.head()

,id,submitter,authors,title,comments,journal-ref,doi,report-no,categories,license,abstract,versions,update_date,authors_parsed
0,704.0001,Pavel Nadolsky,"C. Bal\'azs, E. L. Berger, P. M. Nadolsky, C.-...",Calculation of prompt diphoton production cros...,"37 pages, 15 figures; published version","Phys.Rev.D76:013009,2007",10.1103/PhysRevD.76.013009,ANL-HEP-PR-07-12,hep-ph,NaN,A fully differential calculation in perturba...,"[{'version': 'v1', 'created': 'Mon, 2 Apr 2007...",2008-11-26,"[['Balázs', 'C.', ''], ['Berger', 'E. L.', '']..."
1,704.0002,Louis Theran,Ileana Streinu and Louis Theran,Sparsity-certifying Graph Decompositions,To appear in Graphs and Combinatorics,NaN,NaN,NaN,math.CO cs.CG,http://arxiv.org/licenses/nonexclusive-distrib...,"We describe a new algorithm, the $(k,\ell)$-...","[{'version': 'v1', 'created': 'Sat, 31 Mar 200...",2008-12-13,"[['Streinu', 'Ileana', ''], ['Theran', 'Louis'..."
2,704.0003,Hongjun Pan,Hongjun Pan,The evolution of the Earth-Moon system based o...,"23 pages, 3 figures",NaN,NaN,NaN,physics.gen-ph,NaN,The evolution of Earth-Moon system is descri...,"[{'version': 'v1', 'created': 'Sun, 1 Apr 2007...",2008-01-13,"[['Pan', 'Hongjun', '']]"
3,704.0004,David Callan,David Callan,A determinant of Stirling cycle numbers counts...,11 pages,NaN,NaN,NaN,math.CO,NaN,We show that a determinant of Stirling cycle...,"[{'version': 'v1', 'created': 'Sat, 31 Mar 200...",2007-05-23,"[['Callan', 'David', '']]"
4,704.0005,Alberto Torchinsky,Wael Abu-Shammala and Alberto Torchinsky,From dyadic $\Lambda_{\alpha}$ to $\Lambda_{\a...,NaN,"Illinois J. Math. 52 (2008) no.2, 681-689",NaN,NaN,math.CA math.FA,NaN,In this paper we show how to compute the $\L...,"[{'version': 'v1', 'created': 'Mon, 2 Apr 2007...",2013-10-15,"[['Abu-Shammala', 'Wael', ''], ['Torchinsky', ..."

In [14]:
# drop column id , submitter, authors, journal-ref. doi, report-no
df.drop(['id', 'submitter', 'authors', 'journal-ref', 'doi', 'report-no'], axis=1, inplace=True)
df.head()

,title,comments,categories,license,abstract,versions,update_date,authors_parsed
0,Calculation of prompt diphoton production cros...,"37 pages, 15 figures; published version",hep-ph,NaN,A fully differential calculation in perturba...,"[{'version': 'v1', 'created': 'Mon, 2 Apr 2007...",2008-11-26,"[['Balázs', 'C.', ''], ['Berger', 'E. L.', '']..."
1,Sparsity-certifying Graph Decompositions,To appear in Graphs and Combinatorics,math.CO cs.CG,http://arxiv.org/licenses/nonexclusive-distrib...,"We describe a new algorithm, the $(k,\ell)$-...","[{'version': 'v1', 'created': 'Sat, 31 Mar 200...",2008-12-13,"[['Streinu', 'Ileana', ''], ['Theran', 'Louis'..."
2,The evolution of the Earth-Moon system based o...,"23 pages, 3 figures",physics.gen-ph,NaN,The evolution of Earth-Moon system is descri...,"[{'version': 'v1', 'created': 'Sun, 1 Apr 2007...",2008-01-13,"[['Pan', 'Hongjun', '']]"
3,A determinant of Stirling cycle numbers counts...,11 pages,math.CO,NaN,We show that a determinant of Stirling cycle...,"[{'version': 'v1', 'created': 'Sat, 31 Mar 200...",2007-05-23,"[['Callan', 'David', '']]"
4,From dyadic $\Lambda_{\alpha}$ to $\Lambda_{\a...,NaN,math.CA math.FA,NaN,In this paper we show how to compute the $\L...,"[{'version': 'v1', 'created': 'Mon, 2 Apr 2007...",2013-10-15,"[['Abu-Shammala', 'Wael', ''], ['Torchinsky', ..."

In [15]:
#drop columns comments, license, versions, authors_parsed
df.drop(['comments', 'license', 'versions', 'authors_parsed'], axis=1, inplace=True)
df.head()

,title,categories,abstract,update_date
0,Calculation of prompt diphoton production cros...,hep-ph,A fully differential calculation in perturba...,2008-11-26
1,Sparsity-certifying Graph Decompositions,math.CO cs.CG,"We describe a new algorithm, the $(k,\ell)$-...",2008-12-13
2,The evolution of the Earth-Moon system based o...,physics.gen-ph,The evolution of Earth-Moon system is descri...,2008-01-13
3,A determinant of Stirling cycle numbers counts...,math.CO,We show that a determinant of Stirling cycle...,2007-05-23
4,From dyadic $\Lambda_{\alpha}$ to $\Lambda_{\a...,math.CA math.FA,In this paper we show how to compute the $\L...,2013-10-15

In [16]:
#preprocessing
import pandas as pd
import nltk
import string
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize
from nltk.stem import WordNetLemmatizer

stop_words = set(stopwords.words('english'))
punctuations = set(string.punctuation)

lemmatizer = WordNetLemmatizer()

def preprocess_text(text):
    text = text.lower()
    tokens = word_tokenize(text)
    tokens = [lemmatizer.lemmatize(token) for token in tokens if token not in stop_words and token not in punctuations and token.isalpha()]
    return ' '.join(tokens)  

df['title_clean'] = df['title'].apply(preprocess_text)
df['abstract_clean'] = df['abstract'].apply(preprocess_text)


df.to_csv('research_paper_dataset1.csv', index=False)

df.head()

,title,categories,abstract,update_date,title_clean,abstract_clean
0,Calculation of prompt diphoton production cros...,hep-ph,A fully differential calculation in perturba...,2008-11-26,calculation prompt diphoton production cross s...,fully differential calculation perturbative qu...
1,Sparsity-certifying Graph Decompositions,math.CO cs.CG,"We describe a new algorithm, the $(k,\ell)$-...",2008-12-13,graph decomposition,describe new algorithm k game color use obtain...
2,The evolution of the Earth-Moon system based o...,physics.gen-ph,The evolution of Earth-Moon system is descri...,2008-01-13,evolution system based dark matter field fluid...,evolution system described dark matter field f...
3,A determinant of Stirling cycle numbers counts...,math.CO,We show that a determinant of Stirling cycle...,2007-05-23,determinant stirling cycle number count unlabe...,show determinant stirling cycle number count u...
4,From dyadic $\Lambda_{\alpha}$ to $\Lambda_{\a...,math.CA math.FA,In this paper we show how to compute the $\L...,2013-10-15,dyadic,paper show compute norm using dyadic grid resu...

In [17]:
#drop abstract and title
df.drop(['abstract', 'title'], axis=1, inplace=True)
df.head()

,categories,update_date,title_clean,abstract_clean
0,hep-ph,2008-11-26,calculation prompt diphoton production cross s...,fully differential calculation perturbative qu...
1,math.CO cs.CG,2008-12-13,graph decomposition,describe new algorithm k game color use obtain...
2,physics.gen-ph,2008-01-13,evolution system based dark matter field fluid...,evolution system described dark matter field f...
3,math.CO,2007-05-23,determinant stirling cycle number count unlabe...,show determinant stirling cycle number count u...
4,math.CA math.FA,2013-10-15,dyadic,paper show compute norm using dyadic grid resu...

In [18]:
#adding main_category column
new_column_name = 'main_category'

#NaN values instead 
df[new_column_name] = float('nan')

# Save the updated dataset to a new CSV file
df.to_csv('research_paper_dataset2.csv', index=False)

In [22]:
df1 = pd.read_csv(r'D:\Personal\diksha\6 SEM\NLP-shivi\Buck\research_paper_dataset2.csv', encoding='latin-1')
df1.head()

,categories,update_date,title_clean,abstract_clean,main_category
0,hep-ph,2008-11-26,calculation prompt diphoton production cross s...,fully differential calculation perturbative qu...,NaN
1,math.CO cs.CG,2008-12-13,graph decomposition,describe new algorithm k game color use obtain...,NaN
2,physics.gen-ph,2008-01-13,evolution system based dark matter field fluid...,evolution system described dark matter field f...,NaN
3,math.CO,2007-05-23,determinant stirling cycle number count unlabe...,show determinant stirling cycle number count u...,NaN
4,math.CA math.FA,2013-10-15,dyadic,paper show compute norm using dyadic grid resu...,NaN

In [23]:
import pandas as pd

# Specify the column name to replace NaN values
column_name = 'main_category'

# Replace NaN values with 'News'
df1[column_name].fillna('Research Paper', inplace=True)

# Save the updated dataset to a new CSV file
df1.to_csv('research_paper_dataset3.csv', index=False)

In [24]:
df2 = pd.read_csv(r"D:\Personal\diksha\6 SEM\NLP-shivi\Buck\research_paper_dataset3.csv")
df2.head()

,categories,update_date,title_clean,abstract_clean,main_category
0,hep-ph,2008-11-26,calculation prompt diphoton production cross s...,fully differential calculation perturbative qu...,Research Paper
1,math.CO cs.CG,2008-12-13,graph decomposition,describe new algorithm k game color use obtain...,Research Paper
2,physics.gen-ph,2008-01-13,evolution system based dark matter field fluid...,evolution system described dark matter field f...,Research Paper
3,math.CO,2007-05-23,determinant stirling cycle number count unlabe...,show determinant stirling cycle number count u...,Research Paper
4,math.CA math.FA,2013-10-15,dyadic,paper show compute norm using dyadic grid resu...,Research Paper

In [2]:
#rename title_clean column to Title and make it the first column
import pandas as pd
df = pd.read_csv("combined_final_dataset.csv")

In [3]:
df

,Title,main_category,category,date,description
0,Over 4 Million Americans Roll Up Sleeves For O...,News,U.S. NEWS,2022-09-23,health expert said early predict whether deman...
1,"American Airlines Flyer Charged, Banned For Li...",News,U.S. NEWS,2022-09-23,subdued passenger crew fled back aircraft conf...
2,23 Of The Funniest Tweets About Cats And Dogs ...,News,COMEDY,2022-09-23,dog understand could eaten
3,The Funniest Tweets From Parents This Week (Se...,News,PARENTING,2022-09-23,accidentally put toothpaste toothbrush screame...
4,Woman Who Called Cops On Black Bird-Watcher Lo...,News,U.S. NEWS,2022-09-22,amy cooper accused investment firm franklin te...
...,...,...,...,...,...
380,orbital polarization transition multiorbital m...,Research Paper,cond-mat.str-el,2009-11-13,study interplay crystal field splitting hund c...
381,intelligent life cosmology,Research Paper,physics.pop-ph,2015-05-13,shall present three argument proposition intel...
382,mass radius unseen companion eclipsing binary,Research Paper,astro-ph,2009-06-23,derive mass radius component eclipsing binary ...
383,coulomb excitation unstable nucleus intermedia...,Research Paper,nucl-th,2008-11-26,investigate coulomb excitation state unstable ...
384,intersection body generalized cosine transforms,Research Paper,math.FA,2007-05-23,intersection body represent remarkable class g...